# -*- coding: utf-8 -*-
"""Assignment-4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBR1tKx-xpysDuW28oAfwldmQQfMdI99
"""

import numpy as np
import matplotlib.pyplot as plt
import math
 
x = np.linspace(-2,3,100)
p=np.poly1d([3,-2,1/3])
for i in range(len(x)):
    y=p(x)
 
roots=p.r
A=np.array([roots[0],0])
B=np.array([roots[1],0])
print(A,B)
plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1 + 0.1), A[1] * (1 - 0.1) , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1-0.5), B[1] * (1-0.1) , 'B')
plt.plot(x,y)
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()