# -*- coding: utf-8 -*-
"""Assignment-4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBR1tKx-xpysDuW28oAfwldmQQfMdI99
"""

x = np.linspace(-20, 20, 100)
 
y = 3*x**2 - 2*x + 1/3
 
plt.plot(x,y,label='y=3$x^2$-2x+1/3')
plt.grid()
 
 
plt.plot(1/3,0, 'o')
plt.text(1,0,'c')
 
#show plot
plt.ylim([-1,10])
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()
 
plt.show()