# -*- coding: utf-8 -*-
"""Assignment-4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBR1tKx-xpysDuW28oAfwldmQQfMdI99
"""

import numpy as np
import matplotlib.pyplot as plt
 
import math
 
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
def f(x,a,b,c):
 return a*(x**2)+b*x+c
 
#Parabola parameters
a = 3
b = -2
c = 1/3
 
 
 
# equation - 3x^2-2x+1/3
A=np.array([1/3,0])
B=np.array([1/3,0])
x_AB=line_gen(A,B)
x=np.linspace(-3.9,4.6,0)
y=f(x,a,b,c)
plt.plot(x,y);
plt.plot(cur_x,f(cur_x,a,b,c),'o')
plt.text(cur_x*(1+0.1), f(cur_x,a,b,c),'P')
 
plt.title("Parabola touches the x-axis")
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.grid()
 
plt.show()